// POLYMORPHISM IN C++
// - ONE NAME AND DEFFERENT FORM.
// EX- FUNCTION OVERLOADING, OPERATOR OVERLOADING.
// EX- VIRLUAL FUNTION;

// -->THERE ARE TWO TYPES OF POLYMORHISM.

// 1>COMPILER TIME POLYMORPHISM--->TO ACHIVE COMPILER TIME POLYMORPHISM THERE ARE TWO WAY GIVEN BELOW 
// 1.1> FUNCTION OVERLOADING.
// 1.2> OPERATOR OVERLOADING.

// 2>RUN TIME POLYMORPHISM---->TO ACHIVE RUN TIME POLYMORPHISM THERE IS ONLY ONE WAY GIVEN BELOW 
// 2.1> VIRTUAL FUNCTION.